sudo: required
language: generic 
services:
    - docker

before_install:
  - docker build -t jknighten/udemy-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true jknighten/udemy-docker npm run test -- --coverage